version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_JDBC_URL=spring.datasource.url=jdbc:postgresql://localhost:5432/store-management
      - POSTGRES_PASSWORD=kurtp2000
      - POSTGRES_USER=postgres
      - POSTGRES_DB=store-management
    ports:
      - "5432:5432"